# Generated by Django 4.0.5 on 2022-06-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
