# Generated by Django 4.0.5 on 2022-06-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_submitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studentassignment'),
        ),
    ]
