# Generated by Django 4.0.5 on 2022-06-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_submitassignment_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
