# Generated by Django 4.0.5 on 2022-06-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_submitassignment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='submitAssignment',
        ),
    ]
