# Generated by Django 4.0.5 on 2022-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_submitassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='document',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='question',
            field=models.FileField(null=True, upload_to='document_course_pdf/'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
