# Generated by Django 4.0.5 on 2022-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_mycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
