# Generated by Django 4.0.5 on 2022-07-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_coursequize_coursequiz_rename_quize_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
