# Generated by Django 4.0.5 on 2022-07-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_quizquestions_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='CourseQuiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
    ]
